"""
UltraNeRF Evaluation Script
===========================
Evaluates a trained UltraNeRF model on arbitrary poses without requiring train/val/test splits.

Features:
- Load checkpoint and render from arbitrary poses
- Subsample poses in depth dimension for 3D interpolation
- Save rendered outputs and subsampling indices for reconstruction
- Support for both 2D slices and 3D volumes
- Convex probe geometry support
"""

import os
import sys
import time
import random
import numpy as np
import torch
import matplotlib.pyplot as plt
from tqdm import tqdm, trange
from PIL import Image
import random

from nerf_utils import create_nerf, render_us, set_seed
from unerf_config import config_parser
from sampling import *
import convex_configuration as convex
from evaluation_metrics import VolumeMetrics, evaluate_volume_with_slices, print_evaluation_results, save_metrics_to_file

if torch.cuda.is_available():
    torch.cuda.set_per_process_memory_fraction(0.95)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def get_target(images, img_i, pts_image):
    """ Loads the image as a tensor by its index.
        For convex mode it remaps original image to reflect only points
        along sampling rays according to sampling points (pts_image).
        Sampling points are generated by calling calc_image_sampling_points_convex() method.
        If cache is enabled, it loads from cache."""
    global cached_images
    if not convex.config['use_convex_mode']:
        return images[img_i].transpose(0, 1)  # equivalent to tf.transpose(images[img_i])
    else:
        if convex.config['convex_use_compiled_cache']:
            if cached_images[img_i] is not None:
                out = cached_images[img_i]
            else:
                out = remap_target_for_comparison(images[img_i], pts_image)
                cached_images[img_i] = out
        else:
            out = remap_target_for_comparison(images[img_i], pts_image)

        return out

def visualize_2d_slice(rendering_output, pts_image, W, H, output_path, img_i, mode="eval"):
    """Visualize 2D slice rendering outputs (no target comparison)."""
    plt.figure(figsize=(16, 9))
    
    for j, m in enumerate(list(rendering_output.keys())[:12]):
        plt.subplot(3, 4, j + 1)
        plt.title(m)
        array = rendering_output[m].detach().cpu().numpy()[0, 0].T
        if convex.config['use_convex_mode']:
            array = remap_output_to_original_image(array.T, pts_image, W, H)
        plt.imshow(array)

    plt.savefig(
        os.path.join(output_path, "{}_{}.png".format(mode, img_i)),
        bbox_inches="tight",
        dpi=200,
    )
    plt.close()


def visualize_3d_volume_slices(rendering_output, output_image, pts_image, W, H, D, 
                                output_path, img_i, mode="eval", n_slices=3, 
                                save_volume=True, target_volume=None, nerf_original_vis=True):
    """Visualize random slices from 3D volume and optionally save the full volume."""
    
    # Select random slices to visualize
    indices = random.sample(range(D), min(n_slices, D))
    
    for k in indices:
        plt.figure(figsize=(16, 9))
        
        for j, m in enumerate(list(rendering_output.keys())[:12]):
            plt.subplot(3, 4, j + 1)
            if j == 11 and target_volume is not None:
                plt.title("Target")
                array = target_volume[k]
            else:
                plt.title(m)
                array = rendering_output[m].detach().cpu().numpy()[0, k]
                if convex.config['use_convex_mode'] and nerf_original_vis:
                    array = remap_output_to_original_image(array, pts_image, W, H, 
                                                        _interpolate=1)#, interpolation_method="nearest")
            plt.imshow(array)

        plt.savefig(
            os.path.join(output_path, "{}_{}_{}.png".format(k, mode, img_i)),
            bbox_inches="tight",
            dpi=200,
        )
        plt.close()
    
    # Save full 3D volume if requested
    if save_volume:
        slices = []
        
        for d in range(D):
            array = output_image.detach().cpu().numpy()[0, d]
            if nerf_original_vis:
                slices.append(remap_output_to_original_image(array, pts_image, W, H, _interpolate=1))#, interpolation_method="nearest"))
            else:
                slices.append(array)
        output_volume = np.stack(slices, axis=0)
        #print(f"Output volume min: {output_volume.min()}, max: {output_volume.max()}")
        print(f"Output volume min: {output_volume.min()}, max: {output_volume.max()}")
        # Normalize to [0, 1]
        output_volume = (output_volume - output_volume.min()) / (output_volume.max() - output_volume.min())
        print(f"Output volume min: {output_volume.min()}, max: {output_volume.max()}")
        # ========================= COMPUTE EVALUATION METRICS =========================
        if target_volume is not None:
            print(f"\n{'='*70}")
            print(f"Computing evaluation metrics for {mode} volume {img_i}")
            print(f"{'='*70}")
            
            #print target volume min max
            print(f"Target volume min: {target_volume.min()}, max: {target_volume.max()}")
            
            try:
                # Compute all metrics (3D volume + 2D slices)
                metrics_results = evaluate_volume_with_slices(
                    pred_volume=output_volume,
                    target_volume=target_volume,
                    device=device
                )
                
                # Print metrics to console
                print_evaluation_results(metrics_results)
                
                # Save metrics to text file
                metrics_path = os.path.join(output_path, "metrics_{}_{}.txt".format(mode, img_i))
                save_metrics_to_file(metrics_results, metrics_path)
                
                # Save metrics as numpy dict for later analysis
                metrics_npy_path = os.path.join(output_path, "metrics_{}_{}.npy".format(mode, img_i))
                np.save(metrics_npy_path, metrics_results)
                print(f"Metrics saved to: {metrics_path} and {metrics_npy_path}")
                
            except Exception as e:
                print(f"Warning: Failed to compute metrics: {e}")
                import traceback
                traceback.print_exc()
            
            print(f"{'='*70}\n")
        # ========================= END METRICS COMPUTATION =========================
        
        # Visualize middle slices
        if target_volume is not None:
            # Enhanced visualization with target comparison
            plt.figure(figsize=(20, 8))
            
            # Coronal slice (volume[:, H//2, :])
            plt.subplot(2, 2, 1)
            coronal_pred = output_volume[:, output_volume.shape[1] // 2, :]
            plt.imshow(coronal_pred, cmap='gray')
            plt.title(f'Coronal Middle Slice (Predicted) - Vol {img_i}')
            plt.axis('off')
            
            plt.subplot(2, 2, 2)
            coronal_target = target_volume[:, target_volume.shape[1] // 2, :]
            plt.imshow(coronal_target, cmap='gray')
            plt.title(f'Coronal Middle Slice (Target) - Vol {img_i}')
            plt.axis('off')
            
            # Axial slice (volume[:, :, W//2])
            plt.subplot(2, 2, 3)
            axial_pred = output_volume[:, :, output_volume.shape[2] // 2]
            plt.imshow(axial_pred, cmap='gray')
            plt.title(f'Axial Middle Slice (Predicted) - Vol {img_i}')
            plt.axis('off')
            
            plt.subplot(2, 2, 4)
            axial_target = target_volume[:, :, target_volume.shape[2] // 2]
            plt.imshow(axial_target, cmap='gray')
            plt.title(f'Axial Middle Slice (Target) - Vol {img_i}')
            plt.axis('off')
            
            plt.tight_layout()
        else:
            # Original visualization without target
            plt.figure(figsize=(20, 4))
            plt.subplot(1, 2, 1)
            plt.imshow(output_volume[:, output_volume.shape[1] // 2, :], cmap='gray')
            plt.title(f'Coronal Middle Slice - Vol {img_i}')
            plt.axis('off')
            
            plt.subplot(1, 2, 2)
            plt.imshow(output_volume[:, :, output_volume.shape[2] // 2], cmap='gray')
            plt.title(f'Axial Middle Slice - Vol {img_i}')
            plt.axis('off')
        
        plt.savefig(
            os.path.join(output_path, "middle_cut_{}_{}.png".format(mode, img_i)),
            bbox_inches="tight",
            dpi=200,
        )
        plt.close()
        
        volume_path = os.path.join(output_path, "volume_{}_{}.npy".format(mode, img_i))
        np.save(volume_path, output_volume)
        print(f"Saved {mode} volume shape {output_volume.shape} to: {volume_path}")
        


def parse_convex_args_eval(args):
    """Parses command line arguments for convex mode."""
    convex.config['use_convex_mode'] = False
    if args.use_convex_mode:
        print("Running in convex mode...")
        convex.config['use_convex_mode'] = True
        convex.config['use_mip'] = args.use_mip
        convex.config['full_volume_mode'] = args.full_volume_mode
        convex.config['multires'] = args.multires
        
        # MIP-NeRF elongation parameters
        convex.config['use_elongation'] = args.use_elongation
        convex.config['max_elongation'] = args.max_elongation
        convex.config['mip_voxel_radius_lateral'] = args.mip_voxel_radius_lateral
        convex.config['mip_voxel_radius_depth'] = args.mip_voxel_radius_depth
        
        # Sampling strategy parameters (Phase 2: Concentric circles)
        convex.config['sampling_strategy'] = args.sampling_strategy
        convex.config['n_circles'] = args.n_circles
        convex.config['base_rays_per_circle'] = args.base_rays_per_circle
        convex.config['ray_density_multiplier'] = args.ray_density_multiplier
        convex.config['density_growth_type'] = args.density_growth_type
        
        # Radial path mode (tree-ring sampling)
        convex.config['use_radial_path_mode'] = args.use_radial_path_mode
        if args.use_radial_path_mode and args.sampling_strategy != 'concentric_circles':
            print("WARNING: Radial path mode requires concentric_circles sampling strategy. Forcing it.")
            convex.config['sampling_strategy'] = 'concentric_circles'
            args.sampling_strategy = 'concentric_circles'
        
        if args.convex_n_rays is not None:
            convex.config['convex_n_rays'] = args.convex_n_rays

        if args.convex_n_samples is not None:
            convex.config['convex_n_samples'] = args.convex_n_samples

        if args.convex_center_x is not None and args.convex_center_y is not None:
            convex.config['convex_center'] = (args.convex_center_x, args.convex_center_y)

        if args.convex_fan_angle is not None:
            convex.config['convex_angle'] = args.convex_fan_angle

        if args.convex_big_radius is not None:
            convex.config['convex_radius'] = args.convex_big_radius

        if args.convex_small_radius is not None:
            convex.config['convex_radius2'] = args.convex_small_radius

        if args.convex_scaling is not None:
            convex.config['convex_scaling_x'] = args.convex_scaling
            convex.config['convex_scaling_y'] = args.convex_scaling
            args.convex_scaling_x = args.convex_scaling
            args.convex_scaling_y = args.convex_scaling

        if args.convex_scaling_x is not None:
            convex.config['convex_scaling_x'] = args.convex_scaling_x

        if args.convex_scaling_y is not None:
            convex.config['convex_scaling_y'] = args.convex_scaling_y

        # Is value is None in configuration file use args
        if "convex_use_compiled_cache" not in convex.config or convex.config['convex_use_compiled_cache'] is None:
            convex.config['convex_use_compiled_cache'] = True if args.convex_use_compiled_cache else False

        # Is value is None in configuration file use args
        if "convex_use_compiled_cache_on_the_fly" not in convex.config or convex.config['convex_use_compiled_cache_on_the_fly'] is None:
            convex.config['convex_use_compiled_cache_on_the_fly'] = True if args.convex_use_compiled_cache_on_the_fly else False

        # Is value is None in configuration file use args
        if "convex_save_meta_files" not in convex.config or convex.config['convex_save_meta_files'] is None:
            convex.config['convex_save_meta_files'] = True if args.convex_save_meta_files else False

        if "convex_max_dist" not in convex.config or convex.config['convex_max_dist'] is None:
            convex.config['convex_max_dist'] = 1 / (convex.config['convex_radius'] - convex.config['convex_radius2']) / 0.001
    
    # Debug visualization settings
    if hasattr(args, 'debug_viz_render') and args.debug_viz_render:
        convex.config['debug_viz_render'] = True
    else:
        convex.config['debug_viz_render'] = False

    if convex.config['use_convex_mode']:
        args.N_samples = convex.config['convex_n_samples']

    return args


def subsample_poses_depth(poses, subsample_every_n, full_volume_mode=True):
    """
    Subsample poses in the depth dimension for 3D interpolation.
    
    Args:
        poses: Pose array [N, D, 3, 4] or [N, 3, 4]
        subsample_every_n: Keep every n-th pose in depth dimension (1 = keep all)
        full_volume_mode: Whether using 3D volume mode
    
    Returns:
        subsampled_poses: Subsampled pose array
        kept_indices: Indices of kept poses in original array
        mapping_info: Dictionary with reconstruction metadata
    """
    if not full_volume_mode or subsample_every_n == 1:
        # No subsampling needed
        if poses.ndim == 3:
            # [N, 3, 4] - 2D mode
            all_indices = np.arange(poses.shape[0])
        else:
            # [N, D, 3, 4] - 3D mode but keeping all
            all_indices = np.arange(poses.shape[1])
        
        return poses, all_indices, {
            'subsample_every_n': 1,
            'original_depth': poses.shape[1] if poses.ndim == 4 else poses.shape[0],
            'subsampled_depth': poses.shape[1] if poses.ndim == 4 else poses.shape[0],
            'kept_indices': all_indices
        }
    
    # Full volume mode with subsampling
    assert poses.ndim == 4, f"Expected poses shape [N, D, 3, 4] for full_volume_mode, got {poses.shape}"
    
    N, D, _, _ = poses.shape
    
    # Generate subsampling indices
    kept_indices = np.arange(0, D, subsample_every_n)
    
    # Ensure we always keep the last pose for complete coverage
    if kept_indices[-1] != D - 1:
        kept_indices = np.append(kept_indices, D - 1)
    
    # Subsample
    subsampled_poses = poses[:, kept_indices, :, :]
    
    mapping_info = {
        'subsample_every_n': subsample_every_n,
        'original_depth': D,
        'subsampled_depth': len(kept_indices),
        'kept_indices': kept_indices,
        'volumes_processed': N
    }
    
    print(f"\nSubsampling Info:")
    print(f"  Original depth: {D}")
    print(f"  Subsample every: {subsample_every_n}")
    print(f"  Subsampled depth: {len(kept_indices)}")
    print(f"  Kept indices: {kept_indices}")
    print(f"  Compression ratio: {len(kept_indices)/D:.2%}")
    
    return subsampled_poses, kept_indices, mapping_info

# Parse arguments
parser = config_parser()
parser.add_argument("--poses_path", type=str, required=True,
                    help="Path to poses file (.npy) - shape [N, 3, 4] or [N, D, 3, 4]")
parser.add_argument("--target_path", type=str, default=None,
                    help="Path to target volumes file (.npy) - shape [N, D, H, W] for metrics computation")
parser.add_argument("--output_dir", type=str, default=None,
                    help="Output directory ")
parser.add_argument("--subsample_depth_every_n", type=int, default=1,
                    help="Subsample poses every n slices in depth dimension (1=no subsampling)")
parser.add_argument("--save_subsampling_info", action='store_true', default=True,
                    help="Save subsampling indices and metadata for reconstruction")
parser.add_argument("--visualize_slices", type=int, default=3,
                    help="Number of random slices to visualize per volume")

args = parser.parse_args()

# Evaluation must load a trained model: without a checkpoint, create_nerf would
# silently fall back to the latest checkpoint in basedir/expname or to random weights.
if args.ft_path is None or args.ft_path == "None":
    parser.error("--ft_path is required: path to the trained checkpoint (.tar) to evaluate")
if not os.path.isfile(args.ft_path):
    parser.error(f"--ft_path does not exist: {args.ft_path}")

args = parse_convex_args_eval(args)

def evaluate():
    """Main evaluation function."""
    global cached_images

    set_seed(args.random_seed)

    # Create output directory
    if args.output_dir is None:
        checkpoint_dir = os.path.dirname(args.ft_path)
        args.output_dir = os.path.join(checkpoint_dir, "eval_results")
    os.makedirs(args.output_dir, exist_ok=True)
    
    print("\n" + "="*60)
    print("UltraNeRF EVALUATION")
    print("="*60)
    print(f"Checkpoint: {args.ft_path}")
    print(f"Poses: {args.poses_path}")
    print(f"Target: {args.target_path if args.target_path else 'None (no metrics)'}")
    print(f"Output: {args.output_dir}")
    print(f"Depth subsampling: every {args.subsample_depth_every_n} slice(s)")
    print("="*60 + "\n")
    
    # Load poses
    poses = np.load(args.poses_path)
    print(f"Loaded poses with shape: {poses.shape}")
    poses[..., :3, 3] *= 0.001 # Convert to meters
    
    # Load target volumes if provided (for metrics computation)
    target_volumes = None
    if args.target_path is not None:
        target_volumes = np.load(args.target_path)
        print(f"Loaded target volumes with shape: {target_volumes.shape}")
        
        # Validate target shape
        if args.full_volume_mode:
            if target_volumes.ndim == 3:
                # Expand to 4D: [D, H, W] -> [1, D, H, W]
                target_volumes = np.expand_dims(target_volumes, axis=0)
            # Expected shape: [N, D, H, W]
            print(f"Target volumes: {target_volumes.shape[0]} volumes, {target_volumes.shape[1]} depth slices")
        else:
            # For 2D mode, target should be [N, H, W]
            print(f"Target images: {target_volumes.shape[0]} slices")
    
    # Normalize target volumes to [0, 1] if needed
    if target_volumes is not None:
        #target_volumes = target_volumes.astype(np.float32) / 255.0
        target_volumes = (target_volumes - target_volumes.min()) / (target_volumes.max() - target_volumes.min())
    
    # Validate pose shape
    if args.full_volume_mode:
        if poses.ndim == 3:
            # expand to 4D
            poses = np.expand_dims(poses, axis=0)  # Convert to [1, D, 3, 4] for consistency     
        # [N, D, 3, 4] - 3D volume mode
        N, D, _, _ = poses.shape
        print(f"3D volume mode: {N} volumes, {D} depth slices each")
    else:
        N = poses.shape[-3]
        print(f"2D slice mode: {N} poses")
        
            
    # Subsample poses if requested
    if args.full_volume_mode and args.subsample_depth_every_n > 1:
        poses, kept_indices, mapping_info = subsample_poses_depth(
            poses, 
            args.subsample_depth_every_n, 
            args.full_volume_mode
        )
        
        # Save subsampling info
        if args.save_subsampling_info:
            subsample_info_path = os.path.join(args.output_dir, "subsampling_info.npz")
            np.savez(
                subsample_info_path,
                kept_indices=kept_indices,
                subsample_every_n=args.subsample_depth_every_n,
                original_depth=mapping_info['original_depth'],
                subsampled_depth=mapping_info['subsampled_depth'],
                original_poses_shape=np.array([N, D, 3, 4]),
                subsampled_poses_shape=np.array(poses.shape)
            )
            print(f"\nSaved subsampling info to: {subsample_info_path}")
    else:
        kept_indices = np.arange(poses.shape[1] if args.full_volume_mode else poses.shape[0])
        mapping_info = {
            'subsample_every_n': 1,
            'original_depth': poses.shape[1] if args.full_volume_mode else poses.shape[0],
            'subsampled_depth': poses.shape[1] if args.full_volume_mode else poses.shape[0],
            'kept_indices': kept_indices
        }
    
    # Update convex config with volume mode
    convex.config['full_volume_mode'] = args.full_volume_mode
    
    # Determine image dimensions from args
    if not convex.config['use_convex_mode']:
        H = args.probe_depth
        W = args.probe_width
    else:
        center, cx, cy, num_rays, angle, radius, radius2 = convex.get_convex_settings()
        # Use config values from convex settings
        H = 617
        W = 617 
        print(f"Using convex settings: center={center}, cx={cx}, cy={cy}, num_rays={num_rays}, angle={angle}, radius={radius}, radius2={radius2}")

    
    # Infer depth from poses if in volume mode
    if args.full_volume_mode:
        D = poses.shape[1]  # Now the subsampled depth
    else:
        D = 1
    
    print(f"Image dimensions: W={W}, H={H}, D={D} (after subsampling)")
    
    # Setup scaling
    scaling = 0.001
    near = 0
    
    if not convex.config['use_convex_mode']:
        probe_depth = args.probe_depth * scaling
        probe_width = args.probe_width * scaling
        far = probe_depth
        sy = probe_depth / float(H)
        sx = probe_width / float(W)
    else:
        center, cx, cy, num_rays, angle, radius, radius2 = convex.get_convex_settings()
        sy = convex.config['convex_scaling_y'] * scaling
        sx = convex.config['convex_scaling_x'] * scaling
        far = (radius - radius2) * convex.config['convex_scaling_y'] * scaling
    
    sh = sy
    sw = sx
    print(f"Near: {near}, Far: {far}")
    print(f"Scaling: sx={sx}, sy={sy}")
    
    # Create model
    print("\nCreating NeRF model...")
    render_kwargs_train, render_kwargs_test, start, optimizer, _, embed_fn = create_nerf(
        args, device=device
    )
    
    bds_dict = {"near": near, "far": far}
    render_kwargs_train.update(bds_dict)
    render_kwargs_test.update(bds_dict)
    
    render_kwargs_test['network_fn'].eval()
    
    # Setup convex sampling if needed
    coord_transform = CoordinateTransformer(W - 1, H - 1)
    pts_image = None
    pts_image_volume = None
    
    if convex.config['use_convex_mode']:
        print("\nSetup convex sampling points...")
        pts_image = calc_image_sampling_points_convex(**render_kwargs_test)
        
        img = np.ones((H, W), dtype=np.uint8) * 255
        pts_pixel_coord = coord_transform.image_to_pixel(pts_image)
        ccord = pts_pixel_coord.reshape((-1, 2))
        img[ccord[:, 1], ccord[:, 0]] = 0
        
        pil_img = Image.fromarray(img, "L")
        pil_img.save(os.path.join(args.output_dir, "sampling_points.png"))
        pts_image = pts_pixel_coord
        
        if args.full_volume_mode:
            # Repeat for volume depth
            pts_image_volume = np.repeat(pts_image[None, ...], D, axis=0)
    
    # Radial path mode initialization if needed
    if convex.config.get('use_radial_path_mode', False):
        from sampling import define_rays_concentric_circles, build_radial_paths_from_concentric
        
        print("\n" + "="*60)
        print("INITIALIZING RADIAL PATH MODE")
        print("="*60)
        
        norm_inner_radius = convex.config['convex_radius2'] / convex.config['convex_radius']
        norm_outer_radius = 1.0
        
        radial_origins, radial_directions, radial_metadata = define_rays_concentric_circles(
            n_circles=convex.config['n_circles'],
            inner_radius=norm_inner_radius,
            outer_radius=norm_outer_radius,
            base_rays_per_circle=convex.config['base_rays_per_circle'],
            ray_density_multiplier=convex.config['ray_density_multiplier'],
            density_growth_type=convex.config['density_growth_type']
        )
        
        radial_paths, radial_path_metadata = build_radial_paths_from_concentric(
            radial_metadata,
            include_center=False
        )
        
        convex.config['_radial_origins'] = radial_origins
        convex.config['_radial_directions'] = radial_directions
        convex.config['_radial_metadata'] = radial_metadata
        convex.config['_radial_paths'] = radial_paths
        convex.config['_radial_path_metadata'] = radial_path_metadata
        
        print(f"Initialized {radial_path_metadata['n_paths']} radial paths")
        print("="*60 + "\n")
    
    # Start evaluation
    print("\n" + "="*60)
    print("STARTING EVALUATION")
    print("="*60 + "\n")
    
    eval_start_time = time.time()
    
    with torch.no_grad():
        for vol_idx in trange(N, desc="Evaluating volumes"):
            
            if not args.full_volume_mode:
                # 2D mode: single pose
                pose = torch.from_numpy(poses[vol_idx, :3, :4]).to(device).unsqueeze(0)
            else:
                # 3D mode: volume of poses (now subsampled)
                pose = torch.from_numpy(poses[vol_idx, ..., :3, :4]).to(device).unsqueeze(0)

            # Render
            if convex.config.get('use_radial_path_mode', False):
                """
                from rendering import render_radial_paths
                
                rendering_output = render_radial_paths(
                    origins=convex.config['_radial_origins'],
                    directions=convex.config['_radial_directions'],
                    metadata=convex.config['_radial_metadata'],
                    paths=convex.config['_radial_paths'],
                    path_metadata=convex.config['_radial_path_metadata'],
                    pose=pose.squeeze(0).cpu().numpy(),
                    network_fn=render_kwargs_test['network_fn'],
                    network_query_fn=render_kwargs_test['network_query_fn'],
                    chunk=args.chunk
                )
                """
                # TODO: for potential future spherial or concentric circle sampling strategies, we may need to adjust this reshaping logic
                raise NotImplementedError("Radial path mode rendering output processing not implemented yet")
            else:
                rendering_output = render_us(H, W, sw, sh, c2w=pose, 
                                            chunk=args.chunk, retraw=True, 
                                            **render_kwargs_test)
            
            output_image = rendering_output['intensity_map']
            
            # Visualize and save
            rendering_path = os.path.join(args.output_dir, "renderings")
            os.makedirs(rendering_path, exist_ok=True)
            
            if not args.full_volume_mode:
                # 2D visualization
                visualize_2d_slice(rendering_output, pts_image, W, H, 
                                  rendering_path, vol_idx, mode="eval")
                
                # Save output as numpy
                output_np = output_image.detach().cpu().numpy()[0, 0].T
                if convex.config['use_convex_mode']:
                    output_np = remap_output_to_original_image(output_np.T, pts_image, W, H)
                
                output_path = os.path.join(rendering_path, f"output_{vol_idx:04d}.npy")
                np.save(output_path, output_np)
            else:
                nerf_original_vis = True
                # 3D visualization
                # Get target volume for this index if available
                target_vol = None
                if target_volumes is not None:
                    target_vol = target_volumes[vol_idx]  # Shape: [D, H, W]

                    slices = []
                    for d in range(target_vol.shape[0]):
                        pts_slice = pts_image_volume[d] 
                        slice = get_target(target_vol, d, pts_slice)
                        if nerf_original_vis:
                            slice = remap_output_to_original_image(slice, pts_slice, W, H, _interpolate=1)
                        else:
                            slice = slice
                        slices.append(slice)
                    
                    target_vol = np.stack(slices, axis=0)  # shape: [D, ...]
                                        
                    print(f"Using target volume {vol_idx} with shape {target_vol.shape} for metrics")
                
                visualize_3d_volume_slices(
                    rendering_output, output_image, pts_image,
                    W, H, D, rendering_path, vol_idx,
                    mode="eval", n_slices=args.visualize_slices,
                    save_volume=args.save_volume,
                    target_volume=target_vol,
                    nerf_original_vis=nerf_original_vis
                )
    
    eval_end_time = time.time()
    total_time = eval_end_time - eval_start_time
    
    print("\n" + "="*60)
    print("EVALUATION COMPLETE")
    print("="*60)
    print(f"Total time: {total_time/60:.2f} minutes")
    print(f"Time per volume: {total_time/N:.2f} seconds")
    print(f"Output directory: {args.output_dir}")
    
    if args.full_volume_mode and args.subsample_depth_every_n > 1:
        print(f"\nSubsampling applied:")
        print(f"  Original depth: {mapping_info['original_depth']}")
        print(f"  Subsampled depth: {mapping_info['subsampled_depth']}")
        print(f"  Compression: {mapping_info['subsampled_depth']/mapping_info['original_depth']:.2%}")
        print(f"\nTo reconstruct full resolution:")
        print(f"  1. Load subsampling_info.npz from {args.output_dir}")
        print(f"  2. Use kept_indices to map rendered slices back to original positions")
        print(f"  3. Apply 3D interpolation (e.g., scipy.interpolate.griddata)")
    
    print("="*60 + "\n")
    
    # Save evaluation summary
    summary = {
        'ft_path': args.ft_path,
        'poses_path': args.poses_path,
        'num_volumes': N,
        'depth_per_volume': D,
        'full_volume_mode': args.full_volume_mode,
        'subsample_depth_every_n': args.subsample_depth_every_n,
        'evaluation_time_seconds': total_time,
        'subsampling_info': mapping_info if args.full_volume_mode else None
    }
    
    summary_path = os.path.join(args.output_dir, "evaluation_summary.npz")
    np.savez(summary_path, **summary)
    print(f"Saved evaluation summary to: {summary_path}")


if __name__ == "__main__":
    torch.set_default_dtype(torch.float32)
    torch.set_default_device(device)
    evaluate()
